=== hmrc/pension-scheme-event-reporting/conf/resources.schemas/api-1832-get-member-event-report-response-schema-v1.1.0.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Get Member Event Report Success Response Schema",
    "type": "object", 
    "required": [
          "processingDate",
          "schemeDetails",
          "eventReportDetails"
    ],
    "properties": {
          "processingDate": {
            "type": "string",
            "description": "The date the message was processed",
            "format": "date-time"
          },
          "schemeDetails": {
            "type": "object",
            "required": [
              "pSTR",
              "schemeName"
            ],
            "additionalProperties": false,
            "properties": {
              "pSTR": {
                "type": "string",
                "pattern": "[0-9]{8}[A-Z]{2}"
              },
              "schemeName": {
                "type": "string",
                "minLength": 1,
                "maxLength": 160
              }
            }
          },
          "eventReportDetails": {
            "type": "object",
            "required": [
              "reportStartDate",
              "reportEndDate",
			  "reportStatus",
              "reportVersionNumber",
              "reportSubmittedDateAndTime"
            ],
            "additionalProperties": false,
            "properties": {
              "reportStartDate": {
                "$ref": "#/definitions/dateType"
              },
              "reportEndDate": {
                "$ref": "#/definitions/dateType"
              },
			  "reportStatus": {
				"description": "Possible values are Compiled or Submitted",
				"type": "string",
				"enum": [
					"Compiled",
					"Submitted"
				]
			  },	              
              "reportVersionNumber": {
                "type": "string",
                "pattern": "[0-9]{3}"
              },
              "reportSubmittedDateAndTime": {
                "type": "string",
                "pattern": "[2-9][0-9]{3}-(01|02|03|04|05|06|07|08|09|10|11|12)-([0][1-9]|[1-2][0-9]|[3][0-1])T([0-1][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]Z"
               },
			  "eventType": {
				"description": "Possible values are Event2, Event3, Event4, Event5, Event6, Event7, Event8, Event8A, Event22, Event23, Event24",
				"type": "string",
				"enum": [
					"Event2",
					"Event3",
					"Event4",
					"Event5",
					"Event6",
					"Event7",
					"Event8",
					"Event8A",
					"Event22",
					"Event23",
					"Event24"
				]
			  }
             }
            },  
          "eventDetails":{
             "type":"array",
             "required": [
               	"memberStatus",
			    "event"
             ],
             "minItems":1,
             "title":"eventDetails",
             "items":{
               "type":"object",
               "properties":{
                   "memberDetail":{
                      "type":"object",
                      "required": [
                      	"memberStatus",
                      	"event"
                      ],
                      "additionalProperties":false,
                      "properties":{
                         "amendedVersion":{
                            "$ref":"#/definitions/versionType"
                         },
                         "memberStatus":{
                            "type":"string",
                            "enum":[
                               "New",
                               "Changed",
                               "Deleted"
                            ]
                         },
                         "event":{
                            "oneOf":[
                            {
                               "type":"object",
                               "properties":{
								  "eventType":{
									"type":"string",
									 "enum":[
										"Event2"
									 ]
								   },
								  "individualDetails":{
									 "$ref":"#/definitions/individualDetailsType"
								  },
								  "personReceivedThePayment":{
									 "$ref":"#/definitions/individualDetailsType"
								  },
								  "paymentDetails":{
									 "type":"object",
									 "additionalProperties":false,
									 "properties":{
										"amountPaid":{
										   "$ref":"#/definitions/amountType"
										},
										"eventDate":{
					    				   "$ref":"#/definitions/dateType"
										}
						    	     },
									 "required":[
										"amountPaid",
										"eventDate"
									 ]
								   }
                                },
                                "required":[
								   "eventType",	
                                   "individualDetails",
                                   "personReceivedThePayment",
									"paymentDetails"
                                ],
                                "additionalProperties":false
                            },
                            {
                                "type":"object",
                                "properties":{
                                   "eventType":{
                                      "type":"string",
                                       "enum":[
                                          "Event3"
                                        ]
                                    },
                                    "individualDetails":{
                                         "$ref":"#/definitions/individualDetailsType"
                                     },
                                    "paymentDetails":{
                                        "type":"object",
                                         "additionalProperties":false,
                                         "properties":{
                                             "reasonBenefitTaken":{
                                                "type":"string",
                                                "enum":[
                                                   "Ill Health",
                                                   "Protected Pension Age",
                                                   "Other"
                                                ],
                                                "description":"Possible values are E3-01 - Ill Health, E3-02 - Protected Pension Age, E3-03 - Other"
                                             },                                             	
                                             "amountBenefit":{
                                                "$ref":"#/definitions/amountType"
                                             },
                                             "eventDate":{
                                                "$ref":"#/definitions/dateType"
                                             },
											 "freeText":{
												"$ref":"#/definitions/freeTextType"
											}
                                         },	
										 "required":[
											"reasonBenefitTaken",
											"amountBenefit",
											"eventDate"
										 ]
									   }                                      
                                     },
                                "required":[
								    "eventType",
                                    "individualDetails",
                                    "paymentDetails"
                                ],
                                      "additionalProperties":false
                            },
							{
							   "type":"object",
							   "properties":{
								  "eventType":{
									 "type":"string",
									 "enum":[
										"Event4"
									 ]
								  },
								  "individualDetails":{
									 "$ref":"#/definitions/individualDetailsType"
								  },
								  "paymentDetails":{
									 "type":"object",
									 "additionalProperties":false,
									 "properties":{
										"amountPaid":{
										   "$ref":"#/definitions/amountType"
										},
										"eventDate":{
										   "$ref":"#/definitions/dateType"
										}
									 },
									 "required":[
										"amountPaid",
										"eventDate"
									 ]
								   }
							   },
							   "required":[
									 "eventType",
									 "individualDetails",
									 "paymentDetails"
								  ],
							   "additionalProperties":false
							},
							{
							   "type":"object",
							   "properties":{
								  "eventType":{
									 "type":"string",
									 "enum":[
										"Event5"
									 ]
								  },
								  "individualDetails":{
									 "$ref":"#/definitions/individualDetailsType"
								  },
								  "paymentDetails":{
									 "type":"object",
									 "additionalProperties":false,
									 "properties":{
										"annualRate":{
										   "$ref":"#/definitions/amountType"
										},
										"eventDate":{
										   "$ref":"#/definitions/dateType"
										}
									 },
									 "required":[
											"annualRate",
											"eventDate"
									  ]
								   }
								},
								"required":[
									"eventType",
									"individualDetails",
									"paymentDetails"
								],
								"additionalProperties":false
							},
							{
							   "type":"object",
							   "properties":{
								  "eventType":{
									 "type":"string",
									 "enum":[
										"Event6"
									 ]
								  },
								  "individualDetails":{
									 "$ref":"#/definitions/individualDetailsType"
								  },
								  "paymentDetails":{
									 "type":"object",
									 "additionalProperties":false,
									 "properties":{
										"amountCrystalised":{
										   "$ref":"#/definitions/amountType"
										},
										"typeOfProtection":{
										   "type":"string",
										   "enum":[
											  "Enhanced life time allowance",
											  "Enhanced protection",
											  "Fixed protection",
											  "Fixed protection 2014",
											  "Fixed protection 2016",
											  "Individual protection 2014",
											  "Individual protection 2016"
										   ],
										   "description":"This field is applicable for Event Type 6, Event Type 8 and Event Type 8A. Possible values are E6-01 - Enhanced life time allowance, E6-02 - Enhanced protection, E6-03 - Fixed protection, E6-04 - Fixed protection 2014, E6-05 - Fixed protection 2016, E6-06 - Individual protection 2014, E6-07 - Individual protection 2016"
										},
										"eventDate":{
										   "$ref":"#/definitions/dateType"
										},
										"freeText":{
										   "$ref":"#/definitions/freeTextType"
										}
									 },
									  "required":[
										 "amountCrystalised",
										 "typeOfProtection",
										 "eventDate",
										 "freeText"
									 ] 
								  }
								},  
							   "required":[
								   "eventType",
								   "individualDetails",
								   "paymentDetails"
								],
							   "additionalProperties":false
							},
							{
							   "type":"object",
							   "properties":{
									  "eventType":{
										 "type":"string",
										 "enum":[
											"Event7"
										 ]
									  },
									  "individualDetails":{
										 "$ref":"#/definitions/individualDetailsType"
									  },
									  "paymentDetails":{
										 "type":"object",
										 "additionalProperties":false,
										 "properties":{
												"amountLumpSum":{
												   "$ref":"#/definitions/amountType"
												},
												"amountCrystalised":{
												   "$ref":"#/definitions/amountType"
												},
												"eventDate":{
												   "$ref":"#/definitions/dateType"
												}
										 },
										 "required":[
											 "amountLumpSum",
											 "amountCrystalised",
											 "eventDate"
										]
									  }
							   },	  
								"required":[
									 "eventType",
									 "individualDetails",
									 "paymentDetails"
								 ],
								"additionalProperties":false
							},
							{
							   "type":"object",
							   "properties":{
								  "eventType":{
									 "type":"string",
									 "enum":[
										"Event8"
									 ]
								  },
								  "individualDetails":{
									 "$ref":"#/definitions/individualDetailsType"
								  },
								  "paymentDetails":{
									 "type":"object",
									 "additionalProperties":false,
									 "properties":{
										"typeOfProtection":{
										   "type":"string",
										   "enum":[
											  "Primary Protection",
											  "Enhanced protection"
										   ],
										   "description":"Possible values are E8-01 - Primary Protection, E8-02 - Enhanced protection"
										},
										"amountLumpSum":{
										   "$ref":"#/definitions/amountType"
										},
										"eventDate":{
										   "$ref":"#/definitions/dateType"
										},
										"freeText":{
										   "$ref":"#/definitions/freeTextType"
										}
									  },
									  "required":[
										 "typeOfProtection",
										 "amountLumpSum",
										 "eventDate",
										 "freeText"
									  ]
									}
								  },  
								  "required":[
									 "eventType",
									 "individualDetails",
									 "paymentDetails"
								  ],
								  "additionalProperties":false
							},
							{
							   "type":"object",
							   "properties":{
								  "eventType":{
									 "type":"string",
									 "enum":[
										"Event8A"
									 ]
								  },
								  "individualDetails":{
									 "$ref":"#/definitions/individualDetailsType"
								  },
								  "paymentDetails":{
									 "type":"object",
									 "additionalProperties":false,
									 "properties":{
										"reasonBenefitTaken":{
										   "type":"string",
										   "enum":[
											  "Member where payment of a stand-alone lump sum (100 per lump sum) and the member had protected lump sum rights of more than £375,000 with either primary protection or enhanced protection",
											  "Member where payment of a scheme specific lump sum protection and the lump sum is more than 7.5 per of the lifetime allowance"
										   ],
										   "description":"Possible values are E8A-01 - Member where payment of a stand-alone lump sum (100 per lump sum) and the member had protected lump sum rights of more than £375,000 with either primary protection or enhanced protection, E8A-02 - Member where payment of a scheme specific lump sum protection and the lump sum is more than 7.5 per of the lifetime allowance"
										},
										"typeOfProtection":{
										   "type":"string",
										   "enum":[
											  "Primary Protection",
											  "Enhanced"
										   ],
										   "description":"E8A-01 - Primary ProtectionE8A-02 - Enhanced"
										},
										"amountLumpSum":{
										   "$ref":"#/definitions/amountType"
										},
										"eventDate":{
										   "$ref":"#/definitions/dateType"
										},
										"freeText":{
										   "$ref":"#/definitions/freeTextType"
										}
									 }, 
									 "required":[
										 "eventDate"
									  ]
								  }
							   },
							   "required":[
								   "eventType",
								   "individualDetails",
								   "paymentDetails"
							   ],
							   "additionalProperties":false
							},
							{
							   "type":"object",
							   "properties":{
								  "eventType":{
									 "type":"string",
									 "enum":[
										"Event22",
										"Event23",
										"Event24"
									 ]
								  },
								  "individualDetails":{
									 "$ref":"#/definitions/individualDetailsType"
								  },
								  "paymentDetails":{
									 "type":"object",
									 "additionalProperties":false,
									 "properties":{
										"monetaryAmount":{
										   "$ref":"#/definitions/amountType",
										   "description":"Event 22 - Aggregate Pension Input Amounts for the scheme, Event 23 - Aggregate Pension Input Amounts for money purchase arrangements under the scheme (£), Event 24 - Amount of additional Annual Allowance"
										},
										"taxYearEndingDate":{
										   "$ref":"#/definitions/dateType"
										}
									 },
									 "required":[
									   "taxYearEndingDate"
									 ]
								  }
								},
								"required":[
								   "eventType",
								   "individualDetails",
								   "paymentDetails"
								],
								"additionalProperties":false
							}
                            ]                                	
                                 	
                                 }
                 }
                    }
 
                        }
                    }
              }
    },
    "definitions":{
      "amountType":{
         "type":"number",
         "minimum":0.00,
         "maximum":99999999999.99,
         "multipleOf":0.01
      },
	  "dateType": {
		"type": "string",
		"pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
	  },
      "freeTextType":{
      	"type":"string",
		"minLength":1,
		"maxLength":160,
		"pattern": "^[a-zA-Z0-9\\s\\\\u00C0-\\\\u00FF!#$%&'‘’\\\\\"“”«»()*+,.\\/:;=?@\\\\\\[\\\\\\]£€¥\\\\u005C\\\\u2014\\\\u2013\\\\u2010\\\\u002d]{1,160}$"
      },
      "individualDetailsType":{
         "type":"object",
         "properties":{
            "title":{
               "type":"string",
               "enum":[
                  "Mr",
                  "Mrs",
                  "Miss",
                  "Ms",
                  "Dr",
                  "Sir",
                  "Professor",
                  "Lord"
               ]
            },
            "firstName":{
               "$ref":"#/definitions/nameType"
            },
            "middleName":{
               "$ref":"#/definitions/nameType"
            },
            "lastName":{
               "$ref":"#/definitions/nameType"
            },
            "nino":{
               "type":"string",
               "pattern":"[A-Z]{2}[0-9]{6}[A-Z]{1}",
               "description":"Format example : AA999999A"
            }
         },
         "additionalProperties":false,
         "required":[
            "firstName",
            "lastName",
            "nino"
         ]
      },
      "nameType":{
         "type":"string",
         "pattern":"^[a-zA-Z &`\\\\'\\.^-]{1,35}$"
      },
	  "versionType": {
			"description": "version number from 001 to 999",
			"type": "string",
			"pattern": "^[0-9]{3}$"
	}
   }
}

=== hmrc/pension-scheme-event-reporting/test/resources/api-1832-valid-example.json
{
  "processingDate": "2023-12-15T12:30:46Z",
  "schemeDetails": {
    "pSTR": "87219363YN",
    "schemeName": "Abc Ltd"
  },
  "eventReportDetails": {
    "reportStartDate": "2021-04-06",
    "reportEndDate": "2022-04-05",
    "reportStatus": "Compiled",
    "reportVersionNumber": "001",
    "reportSubmittedDateAndTime": "2023-12-13T12:12:12Z",
    "eventType": "Event22"
  },
  "eventDetails": [
    {
      "memberDetail": {
        "memberStatus": "New",
        "event": {
          "eventType": "Event22",
          "individualDetails": {
            "title": "Mr",
            "firstName": "John",
            "middleName": "A",
            "lastName": "Smith",
            "nino": "AA345678B"
          },
          "paymentDetails": {
            "monetaryAmount": 123.99,
            "taxYearEndingDate": "2021-05-30"
          }
        }
      }
    }
  ]
}
