=== hmrc/pension-scheme-event-reporting/conf/resources.schemas/api-1831-get-event20a-report-response-schema-v1.0.1.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Get Event 20A Report Success Response Schema",
    "type": "object", 
    "required": [
          "processingDate",
          "schemeDetails",
          "er20aDetails",
          "schemeMasterTrustDetails",
          "erDeclarationDetails"
    ],
    "properties": {
          "processingDate": {
            "type": "string",
            "description": "The date the message was processed",
            "format": "date-time"
          },
          "schemeDetails": {
            "type": "object",
            "required": [
              "pSTR",
              "schemeName"
            ],
            "additionalProperties": false,
            "properties": {
              "pSTR": {
                "type": "string",
                "pattern": "[0-9]{8}[A-Z]{2}"
              },
              "schemeName": {
                "type": "string",
                "minLength": 1,
                "maxLength": 160
              }
            }
          },
          "er20aDetails": {
            "type": "object",
            "required": [
              "reportStartDate",
              "reportEndDate",
              "reportVersionNumber",
              "reportSubmittedDateAndTime"
            ],
            "additionalProperties": false,
            "properties": {
              "reportStartDate": {
                "$ref": "#/definitions/dateType"
              },
              "reportEndDate": {
                "$ref": "#/definitions/dateType"
              },
              "reportVersionNumber": {
                "type": "string",
                "pattern": "[0-9]{3}"
              },
              "reportSubmittedDateAndTime": {
                "type": "string",
                "pattern": "[2-9][0-9]{3}-(01|02|03|04|05|06|07|08|09|10|11|12)-([0][1-9]|[1-2][0-9]|[3][0-1])T([0-1][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]Z"
               }
             }
            },   
          "schemeMasterTrustDetails": {
                "oneOf": [
                  {
                    "type": "object",
                    "required": [
                      "startDate"
                    ],
                    "properties": {
                      "startDate": {
                        "$ref": "#/definitions/dateType"
                      }
                    }
                  },
                  {
                    "type": "object",
                    "required": [
                      "ceaseDate"
                    ],
                    "properties": {
                      "ceaseDate": {
                        "$ref": "#/definitions/dateType"

                      }
                    }
                  }
                ]
            },
          "erDeclarationDetails": {
                "type": "object",
                "required": [
                  "submittedBy",
                  "submittedID",
                  "submittedName"
                ],
                "additionalProperties": false,
                "properties": {
                  "submittedBy": {
                    "type": "string",
                    "enum": [
                      "PSA",
                      "PSP"
                    ]
                  },
                  "submittedID": {
                    "type": "string",
                    "pattern": "[A-Za-z0-9]{8}"
                  },
                  "submittedName": {
                    "type": "string",
                    "minLength": 8,
                    "maxLength": 160
                  },
                  "psaDeclaration": {
                    "description": "PSA Declaration is mandatory if the ER20A report is submitted by PSA",
                    "type": "object",
                    "required": [
                      "psaDeclaration1",
                      "psaDeclaration2"
                    ],
                    "additionalProperties": false,
                    "properties": {
                      "psaDeclaration1": {
                        "type": "string",
                        "enum": [
                          "Selected",
                          "Not Selected"
                        ]
                      },
                      "psaDeclaration2": {
                        "type": "string",
                        "enum": [
                          "Selected",
                          "Not Selected"
                        ]
                      }
                    }
                  },
                  "pspDeclaration": {
                    "description": "PSP declaration is mandatory if the ER is submitted by PSP",
                    "type": "object",
                    "required": [
                      "authorisedPSAID",
                      "pspDeclaration1",
                      "pspDeclaration2"
                    ],
                    "additionalProperties": false,
                    "properties": {
                      "authorisedPSAID": {
                        "type": "string",
                        "pattern": "A[0-9]{7}"
                      },
                      "pspDeclaration1": {
                        "type": "string",
                        "enum": [
                          "Selected",
                          "Not Selected"
                        ]
                      },
                      "pspDeclaration2": {
                        "type": "string",
                        "enum": [
                          "Selected",
                          "Not Selected"
                        ]
                      }
                    }
                  }
          
               }
          }
    },
    "definitions": {
		"dateType": {
			"type": "string",
			"pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
		}
    }
}

=== hmrc/pension-scheme-event-reporting/test/resources/api-1831-valid-example.json
{
  "processingDate": "2023-12-15T12:30:46Z",
  "schemeDetails": {
    "pSTR": "87219363YN",
    "schemeName": "Abc Ltd"
  },
  "er20aDetails": {
    "reportStartDate": "2021-04-06",
    "reportEndDate": "2022-04-05",
    "reportVersionNumber": "001",
    "reportSubmittedDateAndTime": "2023-12-13T12:12:12Z"
  },
  "schemeMasterTrustDetails": {
    "startDate": "2021-06-08"
  },
  "erDeclarationDetails": {
    "submittedBy": "PSP",
    "submittedID": "20000001",
    "submittedName": "ABCDEFGHIJKLMNOPQRSTUV",
    "pspDeclaration": {
      "authorisedPSAID": "A4045157",
      "pspDeclaration1": "Selected",
      "pspDeclaration2": "Selected"
    }
  }
}
